# Generated by Django 3.2 on 2021-04-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='response',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
